In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('./train_ver2.csv')

C:\Users\admin\AppData\Local\Temp\ipykernel_22592\203920454.py:1: DtypeWarning: Columns (0: age, 1: antiguedad, 2: indrel_1mes, 3: conyuemp) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('./train_ver2.csv')

In [3]:
data.head()

,fecha_dato,ncodpers,ind_empleado,pais_residencia,sexo,age,fecha_alta,ind_nuevo,antiguedad,indrel,...,ind_hip_fin_ult1,ind_plan_fin_ult1,ind_pres_fin_ult1,ind_reca_fin_ult1,ind_tjcr_fin_ult1,ind_valo_fin_ult1,ind_viv_fin_ult1,ind_nomina_ult1,ind_nom_pens_ult1,ind_recibo_ult1
0,2015-01-28,1375586,N,ES,H,35,2015-01-12,0.0,6,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
1,2015-01-28,1050611,N,ES,V,23,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
2,2015-01-28,1050612,N,ES,V,23,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
3,2015-01-28,1050613,N,ES,H,22,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
4,2015-01-28,1050614,N,ES,V,23,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0

In [4]:
data.shape

(13647309, 48)

In [5]:
goods = [col for col in data.columns if col.startswith('ind_') and col.endswith('_ult1')]
goods

['ind_ahor_fin_ult1',
 'ind_aval_fin_ult1',
 'ind_cco_fin_ult1',
 'ind_cder_fin_ult1',
 'ind_cno_fin_ult1',
 'ind_ctju_fin_ult1',
 'ind_ctma_fin_ult1',
 'ind_ctop_fin_ult1',
 'ind_ctpp_fin_ult1',
 'ind_deco_fin_ult1',
 'ind_deme_fin_ult1',
 'ind_dela_fin_ult1',
 'ind_ecue_fin_ult1',
 'ind_fond_fin_ult1',
 'ind_hip_fin_ult1',
 'ind_plan_fin_ult1',
 'ind_pres_fin_ult1',
 'ind_reca_fin_ult1',
 'ind_tjcr_fin_ult1',
 'ind_valo_fin_ult1',
 'ind_viv_fin_ult1',
 'ind_nomina_ult1',
 'ind_nom_pens_ult1',
 'ind_recibo_ult1']

In [6]:
essentials = data[['fecha_dato', 'ncodpers', 'ind_empleado', 'pais_residencia', 'sexo', 'age', 'tiprel_1mes', 'nomprov', 'renta', 'segmento'] + goods]

In [7]:
set(essentials['age'].dropna())

{'  2',
 '  3',
 '  4',
 '  5',
 '  6',
 '  7',
 '  8',
 '  9',
 ' 10',
 ' 11',
 ' 12',
 ' 13',
 ' 14',
 ' 15',
 ' 16',
 ' 17',
 ' 18',
 ' 19',
 ' 20',
 ' 21',
 ' 22',
 ' 23',
 ' 24',
 ' 25',
 ' 26',
 ' 27',
 ' 28',
 ' 29',
 ' 30',
 ' 31',
 ' 32',
 ' 33',
 ' 34',
 ' 35',
 ' 36',
 ' 37',
 ' 38',
 ' 39',
 ' 40',
 ' 41',
 ' 42',
 ' 43',
 ' 44',
 ' 45',
 ' 46',
 ' 47',
 ' 48',
 ' 49',
 ' 50',
 ' 51',
 ' 52',
 ' 53',
 ' 54',
 ' 55',
 ' 56',
 ' 57',
 ' 58',
 ' 59',
 ' 60',
 ' 61',
 ' 62',
 ' 63',
 ' 64',
 ' 65',
 ' 66',
 ' 67',
 ' 68',
 ' 69',
 ' 70',
 ' 71',
 ' 72',
 ' 73',
 ' 74',
 ' 75',
 ' 76',
 ' 77',
 ' 78',
 ' 79',
 ' 80',
 ' 81',
 ' 82',
 ' 83',
 ' 84',
 ' 85',
 ' 86',
 ' 87',
 ' 88',
 ' 89',
 ' 90',
 ' 91',
 ' 92',
 ' 93',
 ' 94',
 ' 95',
 ' 96',
 ' 97',
 ' 98',
 ' 99',
 ' NA',
 10,
 '100',
 100,
 '101',
 101,
 102,
 '102',
 103,
 '103',
 104,
 '104',
 105,
 '105',
 106,
 '106',
 107,
 '107',
 '108',
 108,
 109,
 '109',
 11,
 110,
 '110',
 111,
 '111',
 112,
 '112',
 113,
 '113',
 114,
 '115',
 115,
 116,
 '116',
 117,
 12,
 126,
 127,
 13,
 14,
 15,
 16,
 163,
 164,
 17,
 18,
 19,
 2,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 3,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 4,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 5,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 6,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 7,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 8,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 9,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99}

In [8]:
essentials['age'] = essentials['age'].dropna().apply(lambda x: float(x) if str(x).strip() != 'NA'
                                            else np.nan)
essentials['age'].head()

0    35.0
1    23.0
2    23.0
3    22.0
4    23.0
Name: age, dtype: float64

In [9]:
# Q1
q1_data = essentials.loc[essentials['fecha_dato']=='2016-05-28'].loc[:, ['nomprov', 'ncodpers', 'renta', 'age']]
q1_data

            nomprov  ncodpers      renta   age
12715856     MADRID    657640  147347.97  68.0
12715857     MADRID    657788  132559.35  42.0
12715858  RIOJA, LA    657795   81399.57  44.0
12715859    BIZKAIA    657790        NaN  42.0
12715860  BARCELONA    657794  102189.00  49.0
...             ...       ...        ...   ...
13647304   ZARAGOZA   1166765   43912.17  22.0
13647305  RIOJA, LA   1166764   23334.99  23.0
13647306   ZARAGOZA   1166763        NaN  47.0
13647307   ZARAGOZA   1166789  199592.82  22.0
13647308     MADRID   1550586        NaN  37.0

[931453 rows x 4 columns]

In [10]:
q1_data = q1_data.dropna()

In [11]:
grouped = q1_data.groupby('nomprov', as_index=True)

customer_num = grouped[['ncodpers',]].count().rename(columns={'ncodpers':'고객 수'})
income_mean = grouped[['renta',]].mean().rename(columns={'renta':'평균 소득'})
income_median = grouped[['renta',]].median().rename(columns={'renta':'소득 중앙값'})
age_mean = grouped[['age',]].mean().rename(columns={'age':'평균 나이'})

In [12]:
features = customer_num.join(income_mean, on='nomprov').join(income_median, on='nomprov').join(age_mean, on='nomprov')
features

                          고객 수          평균 소득      소득 중앙값      평균 나이
nomprov
ALAVA                        9  132838.933333  103321.140  38.000000
ALBACETE                  6346   82970.140154   78566.325  33.278916
ALICANTE                 15559   87142.959076   67332.870  39.715984
ALMERIA                   3080   84851.186250   72932.925  41.030844
ASTURIAS                 12887  101311.341324   87085.140  41.165516
AVILA                     2012   76155.498608   67509.345  37.109344
BADAJOZ                   9622   72130.066952   62307.675  31.805758
BALEARS, ILLES            4641  171890.951564  122837.220  41.528765
BARCELONA                71855  164584.843157  130877.160  40.207334
BIZKAIA                     30  110828.564000   97637.505  40.433333
BURGOS                    5272   97780.229124   89299.890  39.079287
CACERES                   6373   75454.406775   67716.000  32.015691
CADIZ                    14608   98772.353515   79068.720  36.425589
CANTABRIA                 7278  121170.217007   95250.510  43.046441
CASTELLON                 4850   79028.432511   66454.080  36.441031
CEUTA                      328  200515.885152  128699.580  44.585366
CIUDAD REAL               6509   70008.773617   62213.970  34.163005
CORDOBA                   7292   85811.520086   69069.090  37.195968
CORUÑA, A                20118  112581.079748   97389.315  34.646883
CUENCA                    2820   69748.533755   66539.715  33.397163
GIPUZKOA                    14  127185.417857   87024.930  37.928571
GIRONA                    4595  145193.823741  108908.340  36.358868
GRANADA                   9007   96544.954543   82354.560  39.355723
GUADALAJARA               3468   95403.940147   92483.205  41.501730
HUELVA                    6279   76732.887707   68897.520  33.195413
HUESCA                    1971   89253.640457   73531.980  37.452055
JAEN                      3378   76996.493517   67777.635  41.245708
LEON                      4365   93490.714165   80953.410  44.158992
LERIDA                    4064   81517.969975   64772.640  33.359498
LUGO                      3637   76458.005733   64304.880  32.233984
MADRID                  252836  178362.993637  138024.135  46.637136
MALAGA                   18179  120920.857735   94961.910  38.568513
MELILLA                    482  149071.944149  117718.365  46.035270
MURCIA                   18426   78943.243629   67794.735  32.993053
NAVARRA                     16  114208.460625   83410.935  35.875000
OURENSE                   3665   83135.325995   79009.830  32.054297
PALENCIA                  2584   93114.083452   86602.185  35.909830
PALMAS, LAS              11353  100171.383055   80591.610  38.920726
PONTEVEDRA               12862  113397.605584   97699.890  33.365418
RIOJA, LA                 4891   99366.831511   89486.910  42.114292
SALAMANCA                 8444  105520.396300   89750.880  35.657982
SANTA CRUZ DE TENERIFE    3334  102131.308182   82331.550  45.578884
SEGOVIA                   2184   98794.885055   89524.470  38.721612
SEVILLA                  32591  117368.868903   92369.460  38.915283
SORIA                      886   87837.921027   78559.230  40.193002
TARRAGONA                 4734  104479.600944   87640.425  40.723701
TERUEL                    1065   88168.578000   76778.040  33.476056
TOLEDO                    9659   80116.487937   68747.730  36.778549
VALENCIA                 36775   89296.188278   72734.910  40.199103
VALLADOLID               13802  101641.794166   92628.285  38.712361
ZAMORA                    2443   83752.301334   74767.500  33.881703
ZARAGOZA                 18917  110172.519208   99607.890  42.066660

In [13]:
features = features[features['고객 수'] >= 50]

# 평균 소득 순으로 내림차순 정렬 후 앞 5개 출력
print(list(features.sort_values(by='평균 소득', ascending=False).iloc[:5].index))

['CEUTA', 'MADRID', 'BALEARS, ILLES', 'BARCELONA', 'MELILLA']

In [14]:
# Q2
q2_data = essentials[['fecha_dato', 'ncodpers']+goods]
q2_data

,fecha_dato,ncodpers,ind_ahor_fin_ult1,ind_aval_fin_ult1,ind_cco_fin_ult1,ind_cder_fin_ult1,ind_cno_fin_ult1,ind_ctju_fin_ult1,ind_ctma_fin_ult1,ind_ctop_fin_ult1,...,ind_hip_fin_ult1,ind_plan_fin_ult1,ind_pres_fin_ult1,ind_reca_fin_ult1,ind_tjcr_fin_ult1,ind_valo_fin_ult1,ind_viv_fin_ult1,ind_nomina_ult1,ind_nom_pens_ult1,ind_recibo_ult1
0,2015-01-28,1375586,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
1,2015-01-28,1050611,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
2,2015-01-28,1050612,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
3,2015-01-28,1050613,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
4,2015-01-28,1050614,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13647304,2016-05-28,1166765,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647305,2016-05-28,1166764,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647306,2016-05-28,1166763,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647307,2016-05-28,1166789,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647308,2016-05-28,1550586,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0.0,0.0,0

In [15]:
q2_data.isna().sum()

fecha_dato               0
ncodpers                 0
ind_ahor_fin_ult1        0
ind_aval_fin_ult1        0
ind_cco_fin_ult1         0
ind_cder_fin_ult1        0
ind_cno_fin_ult1         0
ind_ctju_fin_ult1        0
ind_ctma_fin_ult1        0
ind_ctop_fin_ult1        0
ind_ctpp_fin_ult1        0
ind_deco_fin_ult1        0
ind_deme_fin_ult1        0
ind_dela_fin_ult1        0
ind_ecue_fin_ult1        0
ind_fond_fin_ult1        0
ind_hip_fin_ult1         0
ind_plan_fin_ult1        0
ind_pres_fin_ult1        0
ind_reca_fin_ult1        0
ind_tjcr_fin_ult1        0
ind_valo_fin_ult1        0
ind_viv_fin_ult1         0
ind_nomina_ult1      16063
ind_nom_pens_ult1    16063
ind_recibo_ult1          0
dtype: int64

In [16]:
q2_data = q2_data.sort_values(by=['ncodpers', 'fecha_dato'])
q2_data

,fecha_dato,ncodpers,ind_ahor_fin_ult1,ind_aval_fin_ult1,ind_cco_fin_ult1,ind_cder_fin_ult1,ind_cno_fin_ult1,ind_ctju_fin_ult1,ind_ctma_fin_ult1,ind_ctop_fin_ult1,...,ind_hip_fin_ult1,ind_plan_fin_ult1,ind_pres_fin_ult1,ind_reca_fin_ult1,ind_tjcr_fin_ult1,ind_valo_fin_ult1,ind_viv_fin_ult1,ind_nomina_ult1,ind_nom_pens_ult1,ind_recibo_ult1
416965,2015-01-28,15889,0,0,1,0,0,0,0,0,...,0,0,0,0,1,1,0,0.0,0.0,0
836224,2015-02-28,15889,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0.0,0.0,0
1673961,2015-03-28,15889,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0.0,0.0,0
1882060,2015-04-28,15889,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0.0,0.0,0
3144382,2015-05-28,15889,0,0,1,0,0,0,0,0,...,0,0,0,0,1,1,0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13336818,2016-05-28,1553685,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
13336817,2016-05-28,1553686,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
13336816,2016-05-28,1553687,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
13336815,2016-05-28,1553688,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
13336814,2016-05-28,1553689,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0

In [17]:
na_included_columns = ['ind_nomina_ult1', 'ind_nom_pens_ult1']
q2_data[na_included_columns] = q2_data.groupby('ncodpers')[na_included_columns].ffill()

In [18]:
now = q2_data.iloc[1:]
prev = q2_data.iloc[:-1]

new_sub = (now[['ncodpers',]].values == prev[['ncodpers',]].values) & ((now[goods].values==1) & (prev[goods].values==0))
new_sub = pd.DataFrame(new_sub, columns=goods)

new_sub.sum()

ind_ahor_fin_ult1         2
ind_aval_fin_ult1         4
ind_cco_fin_ult1      69997
ind_cder_fin_ult1       136
ind_cno_fin_ult1      37187
ind_ctju_fin_ult1       490
ind_ctma_fin_ult1      7002
ind_ctop_fin_ult1      3882
ind_ctpp_fin_ult1      2420
ind_deco_fin_ult1      3074
ind_deme_fin_ult1       250
ind_dela_fin_ult1     12707
ind_ecue_fin_ult1     26378
ind_fond_fin_ult1      3699
ind_hip_fin_ult1         75
ind_plan_fin_ult1       618
ind_pres_fin_ult1       147
ind_reca_fin_ult1      9238
ind_tjcr_fin_ult1     69311
ind_valo_fin_ult1      4850
ind_viv_fin_ult1         70
ind_nomina_ult1       73799
ind_nom_pens_ult1     84767
ind_recibo_ult1      153205
dtype: int64

In [19]:
print(list(new_sub.sum().sort_values(ascending=False).index[:5]))

['ind_recibo_ult1', 'ind_nom_pens_ult1', 'ind_nomina_ult1', 'ind_cco_fin_ult1', 'ind_tjcr_fin_ult1']

In [20]:
# Q3
q3_data = essentials.loc[essentials['fecha_dato']=='2016-05-28'].loc[:, ['sexo', 'age', 'segmento', 'ind_empleado', 'tiprel_1mes']+goods]
q3_data

,sexo,age,segmento,ind_empleado,tiprel_1mes,ind_ahor_fin_ult1,ind_aval_fin_ult1,ind_cco_fin_ult1,ind_cder_fin_ult1,ind_cno_fin_ult1,...,ind_hip_fin_ult1,ind_plan_fin_ult1,ind_pres_fin_ult1,ind_reca_fin_ult1,ind_tjcr_fin_ult1,ind_valo_fin_ult1,ind_viv_fin_ult1,ind_nomina_ult1,ind_nom_pens_ult1,ind_recibo_ult1
12715856,H,68.0,02 - PARTICULARES,N,I,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
12715857,H,42.0,02 - PARTICULARES,N,A,0,0,1,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
12715858,V,44.0,02 - PARTICULARES,N,A,0,0,1,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
12715859,V,42.0,02 - PARTICULARES,N,A,0,0,0,0,1,...,0,0,0,0,1,0,0,1.0,1.0,1
12715860,H,49.0,01 - TOP,N,A,0,0,1,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13647304,V,22.0,03 - UNIVERSITARIO,N,I,0,0,1,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647305,V,23.0,03 - UNIVERSITARIO,N,I,0,0,1,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647306,H,47.0,02 - PARTICULARES,N,A,0,0,1,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647307,H,22.0,03 - UNIVERSITARIO,N,I,0,0,1,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647308,H,37.0,NaN,N,NaN,0,0,1,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0

In [21]:
q3_data = q3_data.dropna()

In [22]:
X = q3_data[['sexo', 'age', 'segmento', 'ind_empleado', 'tiprel_1mes']].copy()
def _age_to_categorical(age):
    if age < 30:
        return 'young'
    if age < 65:
        return 'adult'
    return 'senior'
X['age'] = X['age'].apply(_age_to_categorical)
X

         sexo     age            segmento ind_empleado tiprel_1mes
12715856    H  senior   02 - PARTICULARES            N           I
12715857    H   adult   02 - PARTICULARES            N           A
12715858    V   adult   02 - PARTICULARES            N           A
12715859    V   adult   02 - PARTICULARES            N           A
12715860    H   adult            01 - TOP            N           A
...       ...     ...                 ...          ...         ...
13647303    V   young  03 - UNIVERSITARIO            N           I
13647304    V   young  03 - UNIVERSITARIO            N           I
13647305    V   young  03 - UNIVERSITARIO            N           I
13647306    H   adult   02 - PARTICULARES            N           A
13647307    H   young  03 - UNIVERSITARIO            N           I

[924410 rows x 5 columns]

In [23]:
y = q3_data[goods].sum(axis=1)
y = y>=3
y

12715856    False
12715857    False
12715858    False
12715859     True
12715860    False
            ...
13647303    False
13647304    False
13647305    False
13647306    False
13647307    False
Length: 924410, dtype: bool

In [24]:
def observed(feature, target):
    df = pd.DataFrame(feature.values, columns=['feature']).join(pd.DataFrame(target.values, columns=['target']))
    feature_list = list(set(feature))
    target_list = list(set(target))
    observed = [[((df['target']==t) & (df['feature']==f)).sum() for f in feature_list] for t in target_list]
    observed = pd.DataFrame(observed, columns=feature_list, index=target_list)
    return observed

observed(X['age'], y)

       senior   adult   young
False   77785  384071  339565
True    12839  102142    8008

In [25]:
def expected(feature, target):
    feature_list = list(set(feature))
    target_list = list(set(target))
    target_ratio = np.array([(target==t).sum() for t in target_list]) / target.count()
    expected = [[r * (feature==f).sum() for f in feature_list] for r in target_ratio]
    expected = pd.DataFrame(expected, columns=feature_list, index=target_list)
    return expected

expected(X['age'], y)

             senior          adult          young
False  78566.844478  421524.333005  301329.822517
True   12057.155522   64688.666995   46243.177483

In [26]:
def chi2(feature, target):
    ob = observed(feature, target)
    ex = expected(feature, target)
    return (ob - ex)**2 / ex

chi2(X['age'], y)

          senior         adult         young
False   7.780391   3327.808251   4851.590144
True   50.698590  21684.666238  31613.934784

In [27]:
cols = X.columns
chi2_test = [chi2(X[col], y).values.sum() for col in cols]
chi2_test = pd.Series(chi2_test, index=cols)
chi2_test

sexo              3443.992615
age              61536.478399
segmento        124374.223984
ind_empleado      1336.294946
tiprel_1mes     184979.998993
dtype: float64

In [28]:
print(chi2_test.sort_values(ascending=False).index[0])

tiprel_1mes